PHASE_1_PLATOON_1_A = {"PRINCESSLEIA":              None, 
                       "LUKESKYWALKER":             None, 
                       "LOBOT":                     None, 
                       "STORMTROOPERHAN":           None, 
                       "ADMINISTRATORLANDO":        None,
                       "MACEWINDU":                 None, 
                       "ANAKINKNIGHT":              None, 
                       "JEDIKNIGHTGUARDIAN":        None, 
                       "AHSOKATANO":                None, 
                       "BARRISSOFFEE":              None,
                       "FINN":                      None, 
                       "POE":                       None, 
                       "REY":                       None, 
                       "RESISTANCETROOPER":         None,
                       "RESISTANCEPILOT":           None}

PHASE_1_PLATOON_2_A = {"PRINCESSLEIA":              None, 
                       "HOTHREBELSCOUT":            None, 
                       "STORMTROOPERHAN":           None, 
                       "ADMIRALACKBAR":             None, 
                       "HOTHREBELSOLDIER":          None,
                       "JEDIKNIGHTCONSULAR":        None, 
                       "IMAGUNDI":                  None, 
                       "OLDBENKENOBI":              None, 
                       "QUIGONJINN":                None, 
                       "PLOKOON":                   None,
                       "CHIEFNEBIT":                None, 
                       "DATHCHA":                   None, 
                       "JAWA":                      None, 
                       "JAWAENGINEER":              None,
                       "JAWASCAVENGER":             None}

PHASE_1_PLATOON_3_A = {"WEDGEANTILLES":             None, 
                       "BIGGSDARKLIGHTER":          None, 
                       "HOTHREBELSCOUT":            None, 
                       "FULCRUMAHSOKA":             None, 
                       "BISTAN":                    None,
                       "KITFISTO":                  None, 
                       "JEDIKNIGHTCONSULAR":        None, 
                       "LUMINARAUNDULI":            None, 
                       "ADMIRALACKBAR":             None, 
                       "PAO":                       None,
                       "CHIEFCHIRPA":               None, 
                       "EWOKELDER":                 None, 
                       "EWOKSCOUT":                 None, 
                       "TEEBO":                     None,
                       "PAPLOO":                    None}

PHASE_1_PLATOON_4_A = {"JYNERSO":                   None, 
                       "CASSIANANDOR":              None, 
                       "BAZEMALBUS":                None, 
                       "CHIRRUTIMWE":               None, 
                       "K2SO":                      None,
                       "IMAGUNDI":                  None, 
                       "JEDIKNIGHTCONSULAR":        None, 
                       "OLDBENKENOBI":              None, 
                       "QUIGONJINN":                None, 
                       "PLOKOON":                   None,
                       "CLONEWARSCHEWBACCA":        None, 
                       "CORUSCANTUNDERWORLDPOLICE": None, 
                       "CLONESERGEANTPHASEI":       None, 
                       "ANAKINKNIGHT":              None,
                       "AHSOKATANO":                None}